export {
  ROULETTE_AUTHORITATIVE_SCALE,
  ROULETTE_BALL_RADIUS,
  ROULETTE_MODEL_PATH as ROULETTE_ASSET_PATH,
  ROULETTE_RAW_SOURCE_CENTER,
  ROULETTE_ROTATION_AXIS,
  ROULETTE_WHEEL_DIAMETER as ROULETTE_NORMALIZED_DIAMETER,
  ROULETTE_Y_ORIGIN,
} from "../../../lib/roulette-physics-config";
